---
# ansiblefied http://askubuntu.com/questions/457528/how-do-i-create-an-efi-bootable-iso-of-a-customized-version-of-ubuntu
- name: Build Custom ISO
  hosts: all
  gather_facts: false
  sudo: true

  roles:
    - { role: iso_builder }
