---
# ansiblefied http://askubuntu.com/questions/457528/how-do-i-create-an-efi-bootable-iso-of-a-customized-version-of-ubuntu
- name: Build Custom ISO
  hosts: all
  gather_facts: false
  sudo: true

  vars:
    iso_builder_mini:
      iso_basename: mini
      iso_distro_flavor: mini
      iso_url: "http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/installer-amd64/current/images/netboot/mini.iso"

  roles:
    - { role: iso_builder }
